### ISSUE TITLE
CSP directive connect-src 'self' doesn't apply to ws 

### ISSUE THREAD

**Issue by mandibuswell** [ServiceInnovationLab/FamilyServiceDirectorySearchinator#128]
Refused to connect to 'ws://192.168.xxx.xxx:3000/sockjs-node/871/baidi1sp/websocket' because it violates the following Content Security Policy directive: "connect-src 'self' ws://localhost:3000 https://catalogue.data.govt.nz https://api.addressfinder.io". 

"connect-src limits the origins that you can connect to (via XHR, WebSockets, and EventSource)"
however it appears that 'self' only applies to http/s and not to websockets.  therefore when running the  code as a development server using   'npm start' on port 3000  the ws connection to your public ip address will not work. In public/index.html there is already a  ws://localhost:3000 to cover this case, however if you are using a network ip address and not 'localhost' to access the development server this will give you an error.

the workaround is to add your public ip address into the public/index.html page in the CSP directive ie:
ws://192.168.xxx.xxx:3000 such as follows

`<meta http-equiv="Content-Security-Policy" content="font-src https://fonts.googleapis.com https://fonts.gstatic.com; connect-src 'self' ws://192.168.xxx.xxx:3000 ws://localhost:3000 https://catalogue.data.govt.nz https://api.addressfinder.io; style-src 'self' https://api.addressfinder.io https://fonts.googleapis.com https://unpkg.com https://serviceinnovationlab.github.io 'unsafe-inline'; script-src 'self' https://api.addressfinder.io https://serviceinnovationlab.github.io https://unpkg.com 'unsafe-eval' 'unsafe-inline' 'unsafe-inline'; default-src 'none'; img-src 'self' data: https://a.tile.openstreetmap.org https://b.tile.openstreetmap.org https://c.tile.openstreetmap.org https://serviceinnovationlab.github.io https://unpkg.com; child-src 'none'; base-uri https://serviceinnovationlab.github.io; form-action https://serviceinnovationlab.github.io; object-src 'none'; manifest-src 'self';">`

I think this is only an issue if you are running the development server, so in that case manually setting the IP address in the directive would be okay. this could just be added to the markdown file as part of instructions

**Comment by Br3nda** [comment]
I'm not seeing any of these errors.
Are u using the same node version specified in `.nvmrc`?

https://github.com/ServiceInnovationLab/FamilyServiceDirectorySearchinator/blob/master/.nvmrc

**Comment by mandibuswell** [comment]
I am using the latest stable version being "Latest LTS Version: 8.11.2"  I am not sure that this would make a difference as this is part of the CSP standard and is not built automatically. Its coded in the public/index.html page?

**Comment by Br3nda** [comment]
I don't know why you're running the app this way.

I know of two ways to run it -- in dev mode (as per the README) `npm start`

and as static files build from `npm build`

Why are you running other commands? What the purpose?

**Comment by Br3nda** [comment]
The app doesn't have any need to talk to self. i'm sitll not sure why you would want to.
