### ISSUE TITLE
Update Other Solutions instructions for node with express

### ISSUE THREAD

**Issue by mandibuswell** [ServiceInnovationLab/FamilyServiceDirectorySearchinator#129]
Following the node and express deployment options you need to do some addtional steps to get it working because the build/index.html file references the path /FamilyServiceDirectorySearchinator/ .

1) build the assets 
`npm run build`

2) create an index.js file as described under git top directory ie: same level as the 'build' folder 

```
const express = require('express');
const path = require('path');
const app = express();

app.use(express.static(path.join(__dirname, 'build')));

app.get('/', function (req, res) {
  res.sendFile(path.join(__dirname, 'build', 'index.html'));
});

app.listen(9000);
```
Traffic coming in on port 9000 will retrieve the build/index.html  . 'build' is also essentiallly the webserver root and given that index.html has paths relative to <webroot>/FamilyServiceDirectorySearchinator/  in order for this to work you will need to move all the build files except index.html under a directory build/FamilyServiceDirectorySearchinator

```
cd build
mkdir FamilyServiceDirectorySearchinator
mv * FamilyServiceDirectorySearchinator/
mv FamilyServiceDirectorySearchinator/index.html .
```

3) Start the node server 
  ` node index.js`

**Comment by Br3nda** [comment]
Index.html is a generated file, during npm build. Its controlled by package.json.

Why are you trying to run a listening server from a build? I can't work out the purpose here.

**Comment by mandibuswell** [comment]
I was trying to get the service running using a node and express as per the instructions in [Deployment>Other Solutions](https://github.com/ServiceInnovationLab/FamilyServiceDirectorySearchinator#other-solutions) specifically Node and Express.  Because the generated index.html file has references such as 
`<link rel="shortcut icon" href="/FamilyServiceDirectorySearchinator/favicon.ico">`  if you follow the instructions as documented you will get 404 errors, because I believe the webroot essentially is under the `build`  directory.

so the way to fix that is to move the generated files under the build directory  to `build/FamilyServiceDirectorySearchinator/` . It is necessary to leave `build/index.html `in the same place because the  Node file you generate as per the instructions redirects to that.   - Does that make sense.

My end goal is to be able to run the service as a container image as a standalone Node service. I could do it another way it was just that it seemed to be the most straight forward for now.

**Comment by Br3nda** [comment]
The readme boilerplate there comes from the create-react-app we used to create this repo.

If you deploy to another path, i think you can change the package name in package.json. `npm build` uses that when it build it. One way is to set the "homepage", like you see here : https://github.com/ServiceInnovationLab/pancake-frontend/blob/master/package.json

**Comment by Br3nda** [comment]
I'm going to remove the confusing boiler plate from the README -- you'll still have a copy in your fork.
