### ISSUE TITLE
Expandable Service Info

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/FamilyServiceDirectorySearchinator#44]
When a service has a long blurb of text associated, hide the end, but allow the user to expand it.

**Comment by Br3nda** [comment]
I'm mapping these to the functionality in the MSD word doc. I can't work out which this one is. Can you give a bit more info?

**Comment by Br3nda** [comment]
text label "show more"

**Comment by verbman** [comment]
This has been implemented a little differently with a list of service categories (as links) displayed for each service, clicking any of these loads that services url with that service category selected.
