### ISSUE TITLE
Refine proximity (range slider)

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/FamilyServiceDirectorySearchinator#51]
Ability to select: 0-25kms / 25-50kms / 50+kms

As a user, I want to restrict the results show by distance from the address I selected, so I can only see results that are as far as I'm willing to travel

**Comment by dlouise64** [comment]
Use range slider

**Comment by verbman** [comment]
Practically what does 50+ mean, it makes no sense to act as if there's no limit (as there may as well be no address), should I make it to 50-100?
