### ISSUE TITLE
By line/Info What is this site, who is delivering it

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/FamilyServiceDirectorySearchinator#60]
Text for this is in Brenda's emails somewhere

**Comment by sarahneeson** [comment]
Draft text in email from Paul 6/12/17.  Needs to be user tested and reviewed for accessibility/screen reader friendliness? (specifically "click on the link")

**Comment by Br3nda** [comment]
Text from Paul:

 Find Whānau Support - Mobile Site

If you are using a mobile device and are looking for family support services near you then you can use Find Whānau Support, the mobile responsive site for the Ministry of Social Development’s Family Services Directory.

If you are a provider or want to use the enhanced functions of the [Family Services Directory](http://www.familyservices.govt.nz/directory), then please click on the link.
