### ISSUE TITLE
Link to Govt.nz For other government services

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/FamilyServiceDirectorySearchinator#63]

**Comment by dlouise64** [comment]
Put in footer

**Comment by verbman** [comment]
I've done some enquiries around this, it's morphed into two questions:
a) Other items, i.e. contact page, copyright, privacy as per https://webtoolkit.govt.nz/standards/web-usability-standard-1-2/) 
b) Sourcing of appropriate govt.nz image (there's a māori version and a non māori version) 
  i.e. see https://www.govt.nz/ footer for non māori version and digital.govt.nz for māori version (although incidentally linking to the wrong site) ssc.govt.nz has the non version - see http://ssc.govt.nz/govt-brand  - and of course also links incorrectly in their footer)

I've got Nadia chasing this for me...

**Comment by verbman** [comment]
I HAVE THE SVG FOR THIS (we can't use the coat of arms without "permission" - but having the footer with Te Reo as per digital.govt.nz footer was what I was hoping for)

![nzgovt-logo-black@2x.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa83c3ddd41550011802575/125516c66e82c728ace21e0d46e68e9d2c9497e483e6b84ce95ffc952a4d07213146ef696097ec22ba416f43554d4bfd405b5643fbad882af7b73b768a5c58bb843e0926c03503b0aac04ee155e57dd205d0f4ae805ec1ef3724e2898e4e3e1f0d1f8bfa583db2d4.png)
