### ISSUE TITLE
Share this site Facebook, Messenger, Email

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/FamilyServiceDirectorySearchinator#65]

**Comment by Br3nda** [comment]
Could be sharing a service (a permalink). Will need to add OG meta tags.

**Comment by Br3nda** [comment]
TODO:

What text do we want in the OG?
What photo do we want in the OG.

**Comment by sarahneeson** [comment]
![family-services-directory-logo-large.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2613c599d956001145c2b3/125516c66e82c728ace21e0d46ee95972a8e9ae49cecad55ad5ef58764422e612c07b724629cae24b045744c030e0cfb144a4356bcbbd671f3e57862804e0ebcd06e5673c16910ade98318b901ba73dd1ad6e0ee8c44d2f42f67b6d5db1063474f4dcbed5727a19e41c95df742e74453a611336be6712431.png)

**Comment by sarahneeson** [comment]
Checking emails now to see if we have some byline text already to include.  Our logo could be a nice image to use when sharing to Facebook etc.

**Comment by sarahneeson** [comment]
DRAFT;
Photo (our logo)
Headline: Need help? Search the [name for Searchinator goes here]
Byline:  Find social sector providers near you who can help you cope with common issues and needs.

**Comment by Br3nda** [comment]
@verbman Did this one get completed?

**Comment by verbman** [comment]
No the OG tags are not done, I spent a while analysing the project yesterday to see how I could do them easily but from what I can see it requires a bit of structural work to get them into the head tags section nicely
