### ISSUE TITLE
Permalinks

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/FamilyServiceDirectorySearchinator#7]
As a user, I want to click a link for a provider and navigate to a page that i can then share the url with a friend or bookmark for later

**Comment by Br3nda** [comment]
from MSD: Ability to show single provider on map

**Comment by Br3nda** [comment]
I think this also covers "Save the results" functionality that MSD have asked for

**Comment by dlouise64** [comment]
#closes 7
